apiVersion: apps/v1
kind: Deployment
metadata:
  name: neume-billing-service-deployment
  labels:
    app: neume-billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neume-billing-service-pod
  template:
    metadata:
      labels:
        app: neume-billing-service-pod
    spec:
      containers:
        - name: neume-billing-service-container
          image: neume.azurecr.io/neume:v2
          ports:
            - containerPort: 80
      tolerations:
        - key: node.kubernetes.io/network-unavailable
          operator: "Exists"
          effect: "NoSchedule"