name: Build Image and Push to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: service_billing
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: neume.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - run: |
        docker build -t neume.azurecr.io/neume-billing-service:${{ github.sha }} -f service_billing/service_billing .
        docker push neume.azurecr.io/neume-billing-service:${{ github.sha }}
